# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: aabdul-w <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2021/10/09 11:17:02 by aabdul-w          #+#    #+#              #
#    Updated: 2021/10/09 12:55:38 by aabdul-w         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME		= libft.a

SRCS		= ft_memset.c \
			  ft_bzero.c \
			  ft_memcpy.c \
			  ft_memmove.c \
			  ft_memchr.c \
			  ft_memcmp.c \
			  ft_strlen.c \
			  ft_strlcpy.c \
			  ft_strlcat.c \
			  ft_strchr.c \
			  ft_strrchr.c \
			  ft_strnstr.c \
			  ft_strncmp.c \
			  ft_atoi.c \
			  ft_isalpha.c \
			  ft_isdigit.c \
			  ft_isalnum.c \
			  ft_isascii.c \
			  ft_isprint.c \
			  ft_toupper.c \
			  ft_tolower.c \
			  ft_calloc.c \
			  ft_strdup.c \
			  ft_substr.c \
			  ft_strjoin.c \
			  ft_strtrim.c \
			  ft_split.c \
			  ft_itoa.c \
			  ft_strmapi.c \
			  ft_putchar_fd.c \
			  ft_putstr_fd.c \
			  ft_putendl_fd.c \
			  ft_putnbr_fd.c \
			  ft_striteri.c

SRCS_B		= ft_lstnew.c \
			  ft_lstadd_front.c \
			  ft_lstsize.c \
			  ft_lstlast.c \
			  ft_lstadd_back.c \
			  ft_lstdelone.c \
			  ft_lstclear.c \
			  ft_lstiter.c \
			  ft_lstmap.c \

OBJS		= $(SRCS:%.c=%.o)

OBJS_B		= $(SRCS_B:%.c=%.o)


FLAGS		= -Wall -Werror -Wextra

all			: $(NAME)

$(NAME)		: 
			  gcc $(FLAGS) -c $(SRCS) -I ./
			  ar rc $(NAME) $(OBJS)

bonus		: $(NAME)
			  gcc $(FLAGS) -c $(SRCS_B) -I ./
			  ar rc $(NAME) $(OBJS_B)

clean 		: 
			  rm -f $(OBJS) $(OBJS_B)

fclean		: clean
			  rm -f $(NAME)

re			: fclean all

.PHONY		: clean fclean all re
